name: Flutter CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.5'
          channel: 'stable'
      
      - run: flutter pub get
      
      - name: Create .env file
        run: echo "PLACEHOLDER=1" > .env
      
      - name: Ensure platform folders exist
        run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi
      
      - run: flutter build apk --release
