name: Flutter CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.5'
          channel: 'stable'

      - run: flutter pub get

      - name: Generate app icon and splash screen
        run: |
          dart run flutter_launcher_icons
          dart run flutter_native_splash:create

      - name: Create .env file
        run: |
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> .env
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env

      - name: Ensure platform folders exist
        run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi

      - name: Set NAI app label
        run: |
          sed -i 's/android:label="[^"]*"/android:label="NAI"/' android/app/src/main/AndroidManifest.xml

      - run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
